version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"  # Laravel backend
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"  # Vue.js frontend
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

