name: PHP Linting (Pint)
on:
  pull_request:
    branches: [ main ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@latest
        with:
          testMode: true
          configPath: "pint.json"
          pintVersion: 1.16.0